const recipes=[
{id:1,name:"Classic Pancakes",type:"Breakfast",time:20,category:["breakfast","quick","vegetarian"],tag:"Breakfast",cuisine:"American",description:"A simple, reliable recipe with fresh ingredients and plenty of flavor.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:2,name:"Avocado Egg Toast",type:"Breakfast",time:12,category:["breakfast","quick","vegetarian"],tag:"Breakfast",cuisine:"American",description:"A straightforward recipe built for an easy homemade meal.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:3,name:"Berry Yogurt Parfait",type:"Breakfast",time:8,category:["breakfast","quick","vegetarian"],tag:"Breakfast",cuisine:"Mediterranean",description:"A colorful, satisfying recipe that works any day of the week.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:4,name:"Breakfast Burrito",type:"Breakfast",time:20,category:["breakfast","quick","vegetarian"],tag:"Breakfast",cuisine:"Mexican",description:"A quick recipe with bright flavors and simple preparation.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:5,name:"Banana Oatmeal",type:"Breakfast",time:10,category:["breakfast","quick","vegetarian"],tag:"Breakfast",cuisine:"American",description:"A comforting homemade favorite with a little something extra.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:6,name:"Shakshuka",type:"Breakfast",time:25,category:["breakfast","quick","vegetarian"],tag:"Breakfast",cuisine:"Middle Eastern",description:"An easy recipe designed to be made and shared.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:7,name:"Chicken Caesar Wrap",type:"Lunch",time:15,category:["lunch","quick"],tag:"Lunch",cuisine:"American",description:"A simple, reliable recipe with fresh ingredients and plenty of flavor.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:8,name:"Caprese Panini",type:"Lunch",time:15,category:["lunch","quick"],tag:"Lunch",cuisine:"Italian",description:"A straightforward recipe built for an easy homemade meal.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:9,name:"Falafel Pita",type:"Lunch",time:25,category:["lunch","quick"],tag:"Lunch",cuisine:"Middle Eastern",description:"A colorful, satisfying recipe that works any day of the week.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:10,name:"Tuna Rice Bowl",type:"Lunch",time:20,category:["lunch","quick"],tag:"Lunch",cuisine:"Japanese-inspired",description:"A quick recipe with bright flavors and simple preparation.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:11,name:"Tomato Soup & Grilled Cheese",type:"Lunch",time:25,category:["lunch","quick"],tag:"Lunch",cuisine:"American",description:"A comforting homemade favorite with a little something extra.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:12,name:"Veggie Hummus Wrap",type:"Lunch",time:10,category:["lunch","quick"],tag:"Lunch",cuisine:"Mediterranean",description:"An easy recipe designed to be made and shared.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:13,name:"Cinnamon Apple Toast",type:"Snack",time:7,category:["snack","quick","vegetarian"],tag:"Snack",cuisine:"American",description:"A simple, reliable recipe with fresh ingredients and plenty of flavor.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:14,name:"Spiced Popcorn",type:"Snack",time:8,category:["snack","quick","vegetarian"],tag:"Snack",cuisine:"American",description:"A straightforward recipe built for an easy homemade meal.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:15,name:"Guacamole & Chips",type:"Snack",time:10,category:["snack","quick","vegetarian"],tag:"Snack",cuisine:"Mexican",description:"A colorful, satisfying recipe that works any day of the week.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:16,name:"Energy Bites",type:"Snack",time:15,category:["snack","quick","vegetarian"],tag:"Snack",cuisine:"American",description:"A quick recipe with bright flavors and simple preparation.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:17,name:"Cucumber Yogurt Dip",type:"Snack",time:10,category:["snack","quick","vegetarian"],tag:"Snack",cuisine:"Mediterranean",description:"A comforting homemade favorite with a little something extra.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:18,name:"Honey Banana Toast",type:"Snack",time:5,category:["snack","quick","vegetarian"],tag:"Snack",cuisine:"American",description:"An easy recipe designed to be made and shared.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:19,name:"Mango Lassi",type:"Drink",time:5,category:["drink","quick","vegetarian"],tag:"Drink",cuisine:"Indian",description:"A simple, reliable recipe with fresh ingredients and plenty of flavor.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:20,name:"Iced Matcha Latte",type:"Drink",time:5,category:["drink","quick","vegetarian"],tag:"Drink",cuisine:"Japanese-inspired",description:"A straightforward recipe built for an easy homemade meal.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:21,name:"Strawberry Lemonade",type:"Drink",time:10,category:["drink","quick","vegetarian"],tag:"Drink",cuisine:"American",description:"A colorful, satisfying recipe that works any day of the week.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:22,name:"Mint Lime Cooler",type:"Drink",time:7,category:["drink","quick","vegetarian"],tag:"Drink",cuisine:"Mediterranean",description:"A quick recipe with bright flavors and simple preparation.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:23,name:"Cold Brew Latte",type:"Drink",time:5,category:["drink","quick","vegetarian"],tag:"Drink",cuisine:"American",description:"A comforting homemade favorite with a little something extra.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:24,name:"Peach Iced Tea",type:"Drink",time:10,category:["drink","quick","vegetarian"],tag:"Drink",cuisine:"American",description:"An easy recipe designed to be made and shared.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:25,name:"Chocolate Mug Cake",type:"Dessert",time:5,category:["dessert","quick","vegetarian"],tag:"Dessert",cuisine:"American",description:"A simple, reliable recipe with fresh ingredients and plenty of flavor.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:26,name:"Berry Cheesecake Cups",type:"Dessert",time:15,category:["dessert","quick","vegetarian"],tag:"Dessert",cuisine:"American",description:"A straightforward recipe built for an easy homemade meal.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:27,name:"Cinnamon Churro Bites",type:"Dessert",time:20,category:["dessert","quick","vegetarian"],tag:"Dessert",cuisine:"Mexican-inspired",description:"A colorful, satisfying recipe that works any day of the week.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:28,name:"Mango Sticky Rice",type:"Dessert",time:30,category:["dessert","vegetarian"],tag:"Dessert",cuisine:"Thai",description:"A quick recipe with bright flavors and simple preparation.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:29,name:"Lemon Shortbread",type:"Dessert",time:25,category:["dessert","quick","vegetarian"],tag:"Dessert",cuisine:"American",description:"A comforting homemade favorite with a little something extra.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:30,name:"Apple Crisp",type:"Dessert",time:40,category:["dessert","vegetarian"],tag:"Dessert",cuisine:"American",description:"An easy recipe designed to be made and shared.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:31,name:"Chicken Tikka Masala",type:"Dinner",time:45,category:["dinner"],tag:"Dinner",cuisine:"Indian",description:"A simple, reliable recipe with fresh ingredients and plenty of flavor.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:32,name:"Vegetable Pad Thai",type:"Dinner",time:30,category:["dinner"],tag:"Dinner",cuisine:"Thai",description:"A straightforward recipe built for an easy homemade meal.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:33,name:"Beef Bulgogi",type:"Dinner",time:30,category:["dinner"],tag:"Dinner",cuisine:"Korean",description:"A colorful, satisfying recipe that works any day of the week.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:34,name:"Margherita Pizza",type:"Dinner",time:30,category:["dinner"],tag:"Dinner",cuisine:"Italian",description:"A quick recipe with bright flavors and simple preparation.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:35,name:"Salmon Teriyaki",type:"Dinner",time:25,category:["dinner","quick"],tag:"Dinner",cuisine:"Japanese-inspired",description:"A comforting homemade favorite with a little something extra.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]},
{id:36,name:"Chickpea Coconut Curry",type:"Dinner",time:35,category:["dinner"],tag:"Dinner",cuisine:"Indian-inspired",description:"An easy recipe designed to be made and shared.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Main ingredients","Fresh produce","Seasoning","Sauce or topping"],steps:["Prepare the ingredients.","Cook or combine everything as directed.","Adjust seasoning to taste.","Serve and enjoy."]}
]

function getUserRecipes(){return storage("ccRecipes",[])}
function allRecipes(){return [...recipes,...getUserRecipes()]}
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function storage(k,f){try{const x=localStorage.getItem(k);return x===null?f:JSON.parse(x)}catch{return f}}
function renderRecipes(){
 const grid=$("recipeGrid"); if(!grid)return;
 const q=($("searchInput")?.value||"").trim().toLowerCase();
 const f=document.querySelector(".chip.active")?.dataset.filter||"all";
 const visible=allRecipes().filter(r=>(f==="all"||r.category.includes(f))&&[r.name,r.description,r.creator,r.tag,r.cuisine].join(" ").toLowerCase().includes(q));
 grid.innerHTML=visible.map(r=>`<article class="recipe-card"><div class="recipe-image"><img loading="lazy" src="${esc(r.image)}" alt="${esc(r.name)}"><span class="recipe-tag">${esc(r.cuisine||r.tag)}</span></div><div class="recipe-info"><div class="recipe-topline">${r.time} min</div><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><div class="creator">Created by ${esc(r.creator)}</div><a class="recipe-open" href="recipe.html?id=${encodeURIComponent(r.id)}">Open recipe →</a></div></article>`).join("");
 if($("emptyState"))$("emptyState").hidden=visible.length>0;
}
function renderRecipe(){
 const root=$("recipePage"); if(!root)return;
 const raw=new URLSearchParams(location.search).get("id");
 const id=Number(raw);
 const r=allRecipes().find(x=>x.id===id)||allRecipes()[0];
 if(!r)return;
 root.innerHTML=`<a class="back-link" href="discover.html">← All recipes</a><section class="recipe-hero"><img src="${esc(r.image)}" alt="${esc(r.name)}"><div class="recipe-details"><p class="eyebrow">${esc(r.cuisine||"Recipe")}</p><h1>${esc(r.name)}</h1><p class="description">${esc(r.description)}</p><p class="creator-line">Created by <strong>${esc(r.creator)}</strong> · ${r.time} minutes</p></div></section><section class="recipe-body"><div><p class="eyebrow">Ingredients</p><h2>What you need.</h2><ul>${r.ingredients.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><p class="eyebrow">Method</p><h2>How to make it.</h2><ol>${r.steps.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div></section>${r.userCreated?'<p class="saved-note">Saved on this device.</p>':""}`;
}
const leaderboard=[["01","Community Cook","18","640"],["02","Community Cook","16","590"],["03","Community Cook","14","520"],["04","Community Cook","12","480"],["05","Community Cook","10","430"]];
function renderLeaderboard(){const root=$("rankList");if(!root)return;root.innerHTML=leaderboard.map(r=>`<div class="rank-row"><span>${r[0]}</span><strong>${r[1]}</strong><span>${r[2]} cooks</span><span>${r[3]} pts</span></div>`).join("");updateProgress(Math.max(0,Number(storage("ccPoints",0))||0))}
function updateProgress(p){if(!$("userPoints"))return;$("userPoints").textContent=p+" pts";$("progressBar").style.width=Math.min(100,p/250*100)+"%";$("progressText").textContent=p<250?(250-p)+" pts until 250.":"250 pts reached."}
function saveRecipe(e){
 e.preventDefault();
 const form=e.currentTarget;
 const ingredients=form.ingredients.value.split("\n").map(x=>x.trim()).filter(Boolean);
 const steps=form.steps.value.split("\n").map(x=>x.trim()).filter(Boolean);
 if(!ingredients.length||!steps.length)return;
 const recipe={id:Date.now(),name:form.name.value.trim(),time:Math.max(1,Number(form.time.value)||30),category:Array.from(form.category.selectedOptions).map(o=>o.value),tag:form.type.value,cuisine:form.cuisine.value.trim()||"Home cooking",type:form.type.value,description:form.description.value.trim(),creator:form.creator.value.trim()||"Community Cook",image:form.image.value.trim()||"https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1000&q=84",ingredients,steps,userCreated:true};
 const saved=getUserRecipes();saved.push(recipe);localStorage.setItem("ccRecipes",JSON.stringify(saved));
 form.reset();form.querySelector(".form-message").textContent="Recipe saved. It now appears in your recipe library.";
 form.querySelector(".form-message").classList.add("show");
}
document.addEventListener("click",e=>{const c=e.target.closest(".chip");if(c){document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));c.classList.add("active");renderRecipes()}});
$("searchInput")?.addEventListener("input",renderRecipes);
$("joinChallenge")?.addEventListener("click",e=>{localStorage.setItem("ccChallenge","true");e.currentTarget.textContent="Joined";$("challengeStatus").textContent="Challenge joined. Now cook your version."});
if($("joinChallenge")&&localStorage.getItem("ccChallenge")==="true")$("joinChallenge").textContent="Joined";
$("logCook")?.addEventListener("click",()=>{const p=(Number(storage("ccPoints",0))||0)+30;localStorage.setItem("ccPoints",String(p));updateProgress(p);$("progressMessage").textContent="+30 points. Cook logged."});
$("recipeForm")?.addEventListener("submit",saveRecipe);
renderRecipes();renderRecipe();renderLeaderboard();