const recipes=[
{id:1,name:"Weeknight Grain Bowl",time:25,category:["quick","vegetarian","budget"],tag:"Weeknight",cuisine:"Mediterranean",description:"Roasted vegetables, warm grains, lemon dressing, and herbs.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=84",ingredients:["2 cups cooked grains","1 cup roasted vegetables","2 cups greens","2 tbsp lemon dressing","Fresh herbs"],steps:["Roast the vegetables until browned and tender.","Warm the grains and prepare the greens.","Build the bowl and add the dressing.","Finish with herbs and lemon."]},
{id:2,name:"Tomato Butter Pasta",time:22,category:["quick","budget"],tag:"Weeknight",cuisine:"Italian",description:"Silky tomato sauce with browned butter, parmesan, and cracked pepper.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=84",ingredients:["8 oz pasta","1 cup tomato sauce","2 tbsp butter","Parmesan","Black pepper"],steps:["Cook the pasta until just tender.","Brown the butter in a pan.","Add tomato sauce and simmer.","Toss with pasta and finish with parmesan."]},
{id:3,name:"Crisp Chickpea Salad",time:15,category:["quick","vegetarian","budget"],tag:"15 minutes",cuisine:"Mediterranean",description:"Crunchy chickpeas, cucumber, herbs, and a bright tahini dressing.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=84",ingredients:["1 can chickpeas","1 cucumber","Fresh herbs","2 tbsp tahini","Lemon juice"],steps:["Drain and rinse the chickpeas.","Chop cucumber and herbs.","Whisk tahini with lemon juice.","Toss everything together and serve."]},
{id:4,name:"Skillet Chicken & Rice",time:38,category:["budget"],tag:"Dinner",cuisine:"American",description:"Golden chicken, toasted rice, garlic, and greens in one skillet.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?auto=format&fit=crop&w=1000&q=84",ingredients:["Chicken thighs","1 cup rice","Garlic","2 cups broth","Greens"],steps:["Brown the chicken in a skillet.","Toast the rice with garlic.","Add broth and return the chicken.","Cover until the rice is tender and finish with greens."]},
{id:5,name:"Charred Corn Tacos",time:27,category:["quick","vegetarian"],tag:"Quick",cuisine:"Mexican",description:"Charred corn, black beans, lime crema, and crunchy cabbage.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?auto=format&fit=crop&w=1000&q=84",ingredients:["Corn tortillas","1 cup corn","1 cup black beans","Cabbage","Lime"],steps:["Char the corn in a hot pan.","Warm the tortillas.","Layer beans, corn, and cabbage.","Finish with lime."]},
{id:6,name:"Lemon Herb Roast",time:52,category:["budget"],tag:"Weekend",cuisine:"American",description:"A simple roast with lemon, rosemary, crisp potatoes, and pan juices.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=84",ingredients:["Chicken or vegetables","Potatoes","Lemon","Rosemary","Olive oil"],steps:["Heat the oven and prepare the tray.","Season everything with lemon, rosemary, and oil.","Roast until browned and tender.","Rest briefly before serving."]},
{id:7,name:"Coconut Curry Noodles",time:30,category:["quick","vegetarian"],tag:"30 minutes",cuisine:"Thai-inspired",description:"Rice noodles, coconut curry broth, lime, and crisp vegetables.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=1000&q=84",ingredients:["Rice noodles","1 can coconut milk","Curry paste","Mixed vegetables","Lime"],steps:["Cook the noodles according to the package.","Simmer coconut milk with curry paste.","Add vegetables and cook until crisp-tender.","Add noodles and finish with lime."]},
{id:8,name:"Chicken Tikka Wraps",time:35,category:["quick"],tag:"Dinner",cuisine:"Indian-inspired",description:"Spiced chicken, cooling yogurt, cucumber, and herbs in warm flatbread.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=1000&q=84",ingredients:["Chicken breast","Yogurt","Garam masala","Flatbread","Cucumber and herbs"],steps:["Marinate chicken with yogurt and spices.","Cook chicken until browned and cooked through.","Warm the flatbread.","Fill with chicken, cucumber, yogurt, and herbs."]},
{id:9,name:"Teriyaki Salmon Rice Bowls",time:28,category:["quick"],tag:"28 minutes",cuisine:"Japanese-inspired",description:"Glazed salmon over rice with cucumber, sesame, and scallions.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=84",ingredients:["Salmon fillets","Cooked rice","Teriyaki sauce","Cucumber","Sesame and scallions"],steps:["Cook the rice and slice the cucumber.","Pan-sear the salmon.","Brush with teriyaki sauce and let it glaze.","Serve over rice with cucumber and scallions."]},
{id:10,name:"Mushroom Miso Udon",time:20,category:["quick","vegetarian"],tag:"20 minutes",cuisine:"Japanese-inspired",description:"Chewy udon, mushrooms, greens, and a savory miso broth.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1000&q=84",ingredients:["Udon noodles","Mushrooms","Miso paste","Vegetable broth","Greens"],steps:["Bring broth to a gentle simmer.","Whisk in miso without boiling hard.","Add mushrooms and greens.","Add cooked udon and serve hot."]},
{id:11,name:"Greek Lemon Potatoes",time:45,category:["vegetarian","budget"],tag:"Side",cuisine:"Greek",description:"Roasted potatoes with lemon, oregano, garlic, and a crisp edge.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=1000&q=84",ingredients:["Potatoes","Lemon juice","Garlic","Oregano","Olive oil"],steps:["Cut potatoes into wedges.","Toss with lemon, garlic, oregano, and oil.","Roast until deeply golden.","Finish with another squeeze of lemon."]},
{id:12,name:"Black Bean Quesadillas",time:18,category:["quick","vegetarian","budget"],tag:"18 minutes",cuisine:"Mexican",description:"Crisp tortillas packed with black beans, cheese, corn, and salsa.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1618040996337-56904b7850b9?auto=format&fit=crop&w=1000&q=84",ingredients:["Flour tortillas","Black beans","Shredded cheese","Corn","Salsa"],steps:["Mash the beans lightly.","Layer beans, cheese, and corn on a tortilla.","Fold and toast until crisp on both sides.","Slice and serve with salsa."]},
{id:13,name:"Korean-Style Beef Rice Bowls",time:30,category:["quick","budget"],tag:"30 minutes",cuisine:"Korean-inspired",description:"Savory ground beef, rice, cucumber, scallions, and a sweet-spicy sauce.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1000&q=84",ingredients:["Ground beef","Cooked rice","Soy sauce","Cucumber","Scallions"],steps:["Brown the beef in a skillet.","Add soy sauce and the remaining sauce ingredients.","Cook until glossy and fragrant.","Serve over rice with cucumber and scallions."]},
{id:14,name:"Roasted Vegetable Couscous",time:32,category:["vegetarian","budget"],tag:"Easy dinner",cuisine:"North African-inspired",description:"Pearl couscous with roasted vegetables, chickpeas, herbs, and lemon.",creator:"Community Cooks",image:"https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=84",ingredients:["Pearl couscous","Mixed vegetables","Chickpeas","Parsley","Lemon"],steps:["Roast the vegetables until caramelized.","Cook the couscous.","Toss couscous with chickpeas and vegetables.","Finish with parsley and lemon."]}
];

function getUserRecipes(){return storage("ccRecipes",[])}
function allRecipes(){return [...recipes,...getUserRecipes()]}
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function storage(k,f){try{const x=localStorage.getItem(k);return x===null?f:JSON.parse(x)}catch{return f}}
function renderRecipes(){
 const grid=$("recipeGrid"); if(!grid)return;
 const q=($("searchInput")?.value||"").trim().toLowerCase();
 const f=document.querySelector(".chip.active")?.dataset.filter||"all";
 const visible=allRecipes().filter(r=>(f==="all"||r.category.includes(f)||(f==="quick"&&r.time<30))&&[r.name,r.description,r.creator,r.tag,r.cuisine].join(" ").toLowerCase().includes(q));
 grid.innerHTML=visible.map(r=>`<article class="recipe-card"><div class="recipe-image"><img loading="lazy" src="${esc(r.image)}" alt="${esc(r.name)}"><span class="recipe-tag">${esc(r.cuisine||r.tag)}</span></div><div class="recipe-info"><div class="recipe-topline">${r.time} min</div><h2>${esc(r.name)}</h2><p>${esc(r.description)}</p><div class="creator">Created by ${esc(r.creator)}</div><a class="recipe-open" href="recipe.html?id=${encodeURIComponent(r.id)}">Open recipe →</a></div></article>`).join("");
 if($("emptyState"))$("emptyState").hidden=visible.length>0;
}
function renderRecipe(){
 const root=$("recipePage"); if(!root)return;
 const raw=new URLSearchParams(location.search).get("id");
 const id=Number(raw);
 const r=allRecipes().find(x=>x.id===id)||allRecipes()[0];
 if(!r)return;
 root.innerHTML=`<a class="back-link" href="discover.html">← All recipes</a><section class="recipe-hero"><img src="${esc(r.image)}" alt="${esc(r.name)}"><div class="recipe-details"><p class="eyebrow">${esc(r.cuisine||"Recipe")}</p><h1>${esc(r.name)}</h1><p class="description">${esc(r.description)}</p><p class="creator-line">Created by <strong>${esc(r.creator)}</strong> · ${r.time} minutes</p></div></section><section class="recipe-body"><div><p class="eyebrow">Ingredients</p><h2>What you need.</h2><ul>${r.ingredients.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div><div><p class="eyebrow">Method</p><h2>How to make it.</h2><ol>${r.steps.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div></section>${r.userCreated?'<p class="saved-note">Saved on this device.</p>':""}`;
}
const leaderboard=[["01","Community Cook","18","640"],["02","Community Cook","16","590"],["03","Community Cook","14","520"],["04","Community Cook","12","480"],["05","Community Cook","10","430"]];
function renderLeaderboard(){const root=$("rankList");if(!root)return;root.innerHTML=leaderboard.map(r=>`<div class="rank-row"><span>${r[0]}</span><strong>${r[1]}</strong><span>${r[2]} cooks</span><span>${r[3]} pts</span></div>`).join("");updateProgress(Math.max(0,Number(storage("ccPoints",0))||0))}
function updateProgress(p){if(!$("userPoints"))return;$("userPoints").textContent=p+" pts";$("progressBar").style.width=Math.min(100,p/250*100)+"%";$("progressText").textContent=p<250?(250-p)+" pts until 250.":"250 pts reached."}
function saveRecipe(e){
 e.preventDefault();
 const form=e.currentTarget;
 const ingredients=form.ingredients.value.split("\n").map(x=>x.trim()).filter(Boolean);
 const steps=form.steps.value.split("\n").map(x=>x.trim()).filter(Boolean);
 if(!ingredients.length||!steps.length)return;
 const recipe={id:Date.now(),name:form.name.value.trim(),time:Math.max(1,Number(form.time.value)||30),category:Array.from(form.category.selectedOptions).map(o=>o.value),tag:"Community",cuisine:form.cuisine.value.trim()||"Home cooking",description:form.description.value.trim(),creator:form.creator.value.trim()||"Community Cook",image:form.image.value.trim()||"https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1000&q=84",ingredients,steps,userCreated:true};
 const saved=getUserRecipes();saved.push(recipe);localStorage.setItem("ccRecipes",JSON.stringify(saved));
 form.reset();form.querySelector(".form-message").textContent="Recipe saved. It now appears in your recipe library.";
 form.querySelector(".form-message").classList.add("show");
}
document.addEventListener("click",e=>{const c=e.target.closest(".chip");if(c){document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));c.classList.add("active");renderRecipes()}});
$("searchInput")?.addEventListener("input",renderRecipes);
$("joinChallenge")?.addEventListener("click",e=>{localStorage.setItem("ccChallenge","true");e.currentTarget.textContent="Joined";$("challengeStatus").textContent="Challenge joined. Now cook your version."});
if($("joinChallenge")&&localStorage.getItem("ccChallenge")==="true")$("joinChallenge").textContent="Joined";
$("logCook")?.addEventListener("click",()=>{const p=(Number(storage("ccPoints",0))||0)+30;localStorage.setItem("ccPoints",String(p));updateProgress(p);$("progressMessage").textContent="+30 points. Cook logged."});
$("recipeForm")?.addEventListener("submit",saveRecipe);
renderRecipes();renderRecipe();renderLeaderboard();